### ISSUE TITLE
2D GUI Framework

### ISSUE THREAD

**Issue by kyle-emmerich** [titan-studio/coeus#28]
- [ ] Frame
- [ ] Label
- [ ] Image label
- [ ] Textbox
- [ ] Numerical input
- [ ] Color picker?
- [ ] Checkbox/radio buttons
- [ ] Slider?
- [ ] File handling of some sort

We need a basic GUI for Coeus. For right now this can just contain the basic controls such as buttons, text boxes, labels, checkboxes, and sliders. Later on, it can be expanded to include rich text editing and formatting, window frames, color pickers, and so on.

No hurry on this, especially since the 2D API needs to be completed first, but it would help make demos easier and could be a boon to prototyping.

Jesse, I recommend looking at Coeus.Utility.Event as well. I think you may find that it's pretty feature-packed and would make a GUI system pretty easy.

**Comment by LPGhatguy** [comment]
Clearing this issue for the time being, we'll recreate one for the new Coeus when we reach that point.
